# Generated by Django 2.1.4 on 2018-12-17 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181217_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 19, 2, 26, 926491)),
        ),
    ]
